# Generated by Django 2.1.5 on 2019-01-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='resume',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
