# Generated by Django 2.1.5 on 2019-01-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0002_content_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
