# Generated by Django 2.1.5 on 2019-01-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0003_content_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='short_des',
            field=models.TextField(max_length=700),
        ),
    ]
