# Generated by Django 2.1.5 on 2019-01-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0004_auto_20190121_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='short_des',
            field=models.TextField(),
        ),
    ]
