# Generated by Django 2.1.5 on 2019-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0005_auto_20190121_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='interest',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='skill',
            field=models.TextField(null=True),
        ),
    ]
