# Generated by Django 2.1.5 on 2019-05-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0009_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
