# Generated by Django 2.1.5 on 2019-05-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0010_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('full_des', models.TextField(blank=True)),
                ('tools', models.TextField(blank=True)),
                ('references', models.TextField(blank=True)),
                ('github_link', models.TextField(blank=True)),
                ('category', models.TextField()),
                ('ongoing', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('pic', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
