# Generated by Django 2.1.5 on 2019-05-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0012_auto_20190515_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_lastupdated',
            field=models.DateField(auto_now=True),
        ),
    ]
