# Generated by Django 2.1.5 on 2019-05-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0013_project_description_lastupdated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=50)),
                ('about', models.TextField(blank=True)),
                ('my_expertise', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='tools',
        ),
        migrations.AddField(
            model_name='project',
            name='tools',
            field=models.ManyToManyField(blank=True, to='webs.Tool'),
        ),
    ]
