# Generated by Django 2.1.5 on 2019-05-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0014_auto_20190515_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('file', models.FileField(null=True, upload_to='files/')),
                ('imp', models.BooleanField()),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('imp', models.BooleanField()),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
