# Generated by Django 2.1.5 on 2019-05-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0016_auto_20190518_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='top10s',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('top_list', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
