# Generated by Django 2.1.5 on 2019-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0019_auto_20190528_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=50)),
                ('des', models.TextField(blank=True)),
                ('pic1', models.ImageField(blank=True, upload_to='images/')),
                ('pic2', models.ImageField(blank=True, upload_to='images/')),
                ('pic3', models.ImageField(blank=True, upload_to='images/')),
                ('pic4', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='tags',
            field=models.ManyToManyField(blank=True, to='webs.Tag'),
        ),
    ]
