# Generated by Django 2.1.5 on 2019-06-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webs', '0020_auto_20190528_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='work_experience',
            field=models.TextField(null=True),
        ),
    ]
